### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'manually_verify'

### ISSUE THREAD

**Issue by KonradDanielewski** [lambdaloop/anipose#10]
Hello,

I came across a weird problem. When trying to draw calibration board or calibrate cameras I get the following error:

`(dlc-windowsgpu) C:\Kalibracja_3D>anipose draw-calibration
Drawing calibration board...
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsgpu\Scripts\anipose.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\site-packages\anipose\anipose.py", line 273, in draw_calibration
    img = get_calibration_board_image(config)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\site-packages\anipose\common.py", line 224, in get_calibration_board_image
    board = get_calibration_board(config)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpu\lib\site-packages\anipose\common.py", line 207, in get_calibration_board
    manually_verify=manually_verify)
TypeError: __init__() got an unexpected keyword argument 'manually_verify'`

When this part is added into the config file (either true or false) I get the same error.
 `[manual_verification]
manually_verify = true`

It's probably something mundane, but I cannot solve this issue on my own.

Konrad

**Comment by hanhanhan-kim** [comment]
Hi Konrad,
I'm just another user and not a dev, but I had an issue like this before--did you install `anipose` from PyPi via `pip install anipose`? I found this error went away after I uninstalled with `pip uninstall anipose` and installed the most recent version of `anipose` and [`calligator`](https://github.com/lambdaloop/calligator) from source, i.e. their respective GitHub repos. Just `git clone https://github.com/lambdaloop/calligator.git` and `git clone https://github.com/lambdaloop/anipose.git`, then from each of those directories, run `pip install .` 
If you run `conda list` in your environment you should see that for `anipose` and `calligator`, under `channel` it should say `<develop>` as opposed to `pypi`. Now hopefully you should be able to calibrate the cams and draw calibration boards. I apologize in advance if these steps don't do anything

**Comment by KonradDanielewski** [comment]
Hi,

thank you! This helped. Do you know if it's a problem with my pip version or something?

**Comment by hanhanhan-kim** [comment]
Nope, your `pip` is fine--you're just installing from a local directory, rather than from PyPi. This [link](https://stackoverflow.com/questions/41535915/python-pip-install-from-local-dir) might help.

**Comment by lambdaloop** [comment]
Hi @KonradDanielewski ,

Thank you for filing this issue! 

I think the root issue is that anipose depends on a higher version of calligator, but I haven't updated the dependency properly. 

I have done so now and pushed the latest anipose and calligator to PyPi, so they should work now. 
Try updating them both in your environment.
`pip install --upgrade anipose calligator`

Let me know if this works or not!

**Comment by KonradDanielewski** [comment]
Hi @lambdaloop ,

calibration works now, so I'm closing this issue. Thank you!
