### ISSUE TITLE
error during calibration

### ISSUE THREAD

**Issue by hanhanhan-kim** [lambdaloop/anipose#11]
Hello,
I am using Ubuntu 18.04 and a charuco board to calibrate. I am getting the following error when running `anipose calibrate`:
```
(dlc-anipose) hank-x299@hank-x299:~/src/dlc-utils/examples/beetlepose$ anipose calibrate
Calibrating...
/home/hank-x299/src/dlc-utils/examples/beetlepose/test_1_no_motor
/home/hank-x299/src/dlc-utils/examples/beetlepose/test_1_no_motor/calibration/calibration.toml
/home/hank-x299/src/dlc-utils/examples/beetlepose/test_1_no_motor/calibration/dal_liom_guid_18475996_2020_02_13_20_25_06.mp4
100%|██████████████████████████| 30033/30033 [01:46<00:00, 281.65it/s]
15051 boards detected
/home/hank-x299/src/dlc-utils/examples/beetlepose/test_1_no_motor/calibration/dal_liom_guid_18475997_2020_02_13_20_25_08.mp4
100%|██████████████████████████| 30033/30033 [00:43<00:00, 694.39it/s]
879 boards detected
/home/hank-x299/src/dlc-utils/examples/beetlepose/test_1_no_motor/calibration/dal_liom_guid_19061101_2020_02_13_20_25_09.mp4
100%|██████████████████████████| 30033/30033 [00:58<00:00, 512.92it/s]
3818 boards detected
/home/hank-x299/src/dlc-utils/examples/beetlepose/test_1_no_motor/calibration/dal_liom_guid_19061600_2020_02_13_20_25_10.mp4
100%|██████████████████████████| 30033/30033 [00:49<00:00, 604.37it/s]
2022 boards detected
/home/hank-x299/src/dlc-utils/examples/beetlepose/test_1_no_motor/calibration/dal_liom_guid_19061602_2020_02_13_20_25_11.mp4
100%|██████████████████████████| 30033/30033 [00:49<00:00, 603.06it/s]
2297 boards detected
defaultdict(<class 'int'>,
            {('18475996', '19061101'): 6,
             ('18475996', '19061600'): 38,
             ('19061101', '18475996'): 6,
             ('19061600', '18475996'): 38})
Traceback (most recent call last):
  File "/home/hank-x299/anaconda3/envs/dlc-anipose/bin/anipose", line 11, in <module>
    load_entry_point('anipose', 'console_scripts', 'anipose')()
  File "/home/hank-x299/anaconda3/envs/dlc-anipose/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hank-x299/anaconda3/envs/dlc-anipose/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hank-x299/anaconda3/envs/dlc-anipose/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hank-x299/anaconda3/envs/dlc-anipose/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hank-x299/anaconda3/envs/dlc-anipose/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hank-x299/anaconda3/envs/dlc-anipose/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/hank-x299/anaconda3/envs/dlc-anipose/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hank-x299/src/anipose/anipose/anipose.py", line 115, in calibrate
    calibrate_all(config)
  File "/home/hank-x299/src/anipose/anipose/common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "/home/hank-x299/src/anipose/anipose/common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "/home/hank-x299/src/anipose/anipose/calibrate.py", line 186, in process_session
    n_samp_iter=100, n_samp_full=2000)
  File "/home/hank-x299/src/calligator/calligator/cameras.py", line 1555, in calibrate_rows
    rvecs, tvecs = get_initial_extrinsics(rtvecs)
  File "/home/hank-x299/src/calligator/calligator/utils.py", line 173, in get_initial_extrinsics
    pairs = find_calibration_pairs(graph, source=0)
  File "/home/hank-x299/src/calligator/calligator/utils.py", line 156, in find_calibration_pairs
    for new in graph[item]:
TypeError: 'NoneType' object is not subscriptable
```
My `config.toml` file has the following:
```
[calibration]
# checkerboard / charuco / aruco
board_type = "charuco"

# width and height of grid
board_size = [4, 4]

# number of bits in the markers, if aruco/charuco
board_marker_bits = 4

# number of markers in dictionary, if aruco/charuco
board_marker_dict_number = 50

# length of marker side
# board_marker_length = 0.7 # mm
board_marker_length = 1.4 # mm

# If charuco or checkerboard, square side length
# board_square_side_length = 1.0 # mm
board_square_side_length = 2.0 # mm

[manual_verification]
# true / false
manually_verify = false
```

Any advice addressing this error is appreciated! 
Thanks!

**Comment by lambdaloop** [comment]
Hi @hanhanhan-kim ,

Thank you for filing this issue!

For the calibration videos, Anipose expects them:
(1) to be recorded simultaneously from all cameras
(2) to have each group recorded at the same time to have the same filename, once the camera name is removed

Based on the filenames, it seems that at least (2) does not hold, and perhaps (1) as well

**Comment by hanhanhan-kim** [comment]
Thanks @lambdaloop !
I simply made new calibration videos and `anipose calibrate` worked great! Thanks so much!
