### ISSUE TITLE
TypeError when running 2d filter on tutorial data

### ISSUE THREAD

**Issue by NSGregory** [lambdaloop/anipose#111]
I have anipose installed in a singularity container.  I am testing the installation using the tutorial.  I was able to install without errors and complete the analyze step.  When I move on to the anipose filter-2d step I get this error:

Apptainer> /home/users/ngregory/.local/bin/anipose filter
Filtering tracked points...
/scratch/users/ngregory/hand_demo/hand-demo-unfilled/2019-08-02/pose-2d-filtered/2019-08-02-vid01-camB.h5
Traceback (most recent call last):
  File "/home/users/ngregory/.local/bin/anipose", line 8, in <module>
    sys.exit(cli())
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/anipose/anipose.py", line 147, in filter
    filter_pose_all(config)
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/anipose/common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/anipose/common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/anipose/filter_pose.py", line 388, in process_session
    write_pose_2d(all_points[:, :, 0], metadata, outpath)
  File "/home/users/ngregory/.local/lib/python3.8/site-packages/anipose/filter_pose.py", line 204, in write_pose_2d
    dout.to_hdf(outname, 'df_with_missing', format='table', mode='w')
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 2682, in to_hdf
    pytables.to_hdf(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/pytables.py", line 305, in to_hdf
    f(store)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/pytables.py", line 287, in <lambda>
    f = lambda store: store.put(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/pytables.py", line 1116, in put
    self._write_to_group(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/pytables.py", line 1766, in _write_to_group
    s.write(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/pytables.py", line 4284, in write
    table = self._create_axes(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/pytables.py", line 3933, in _create_axes
    data_converted = _maybe_convert_for_string_atom(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/pytables.py", line 4975, in _maybe_convert_for_string_atom
    raise TypeError(
TypeError: Cannot serialize the column [('DLC_resnet50_hand-demo-dlcAug5shuffle1_700000', 'base', 'x')]
because its data contents are not [string] but [floating] object type

This command does generate the following files:
Apptainer> cd pose-2d-filtered/
Apptainer> ls
2019-08-02-vid01-camA.h5  2019-08-02-vid01-camB.h5

I seem to be able to run the "label-2d" command without issue.

**Comment by ET12138** [comment]
I have the same problem, can anyone solve it？

**Comment by XT489** [comment]
same problem

**Comment by ZiyiZhang0912** [comment]
same problem

**Comment by jtHJT** [comment]
> 同样的问题

Hello, have you solved it?

**Comment by jtHJT** [comment]
> 同样的问题

Hello, have you solved it?

**Comment by jtHJT** [comment]
Hello, have you solved it?

**Comment by Wulin-Tan** [comment]
same problem

**Comment by abigrassler** [comment]
It looks like a fix for this was merged in yesterday in https://github.com/lambdaloop/anipose/commit/4eeaa9a84da68f3dbffe3326ac455ca335e660c0. This hasn't been released, so if you want to pull it in you'll need to uninstall Anipose in your conda environment, pull this repository, and then do `pip install -e .` inside the repository to install Anipose from source. (The `-e` is optional -- it just means to install it such that if you were to pull again the package would be automatically updated. It's not a magic flag that makes this work.)

@lambdaloop Perhaps could include this in release notes, or push out a 1.0.2 if it's not too difficult?

**Comment by lambdaloop** [comment]
@abigrassler You're right, I'm surprised you noticed it so fast! Thank you for pointing me to this issue again.

I'm sorry for such a long running issue. I couldn't really understand where it was coming from until I installed anipose in a new environment recently and encountered it. I think there's some issue with the new pandas that makes it break.

I'll push an updated version of anipose this week with this fix.

**Comment by SRCM-lab** [comment]
Hi!

I am currently experiencing the same error (Both during the tutorial, and when working on our own data). 
I can also run "anipose label-2d", without an issue, but anipose seems to need the filtered data, for the triangulation step, so I have gone back to try to fix this error.

I do get a H5 file during the "anipose filter" step, but it does not seem to be correctly made, since neither the "anipose label-2d-filter", nor the triangulation step recognizes it. Anipose label-2d-filter produces the following error: 
[(anipose_clone)_Label-2d-filter.txt](https://github.com/user-attachments/files/16247320/anipose_clone._Label-2d-filter.txt)
I also get a `TypeError: cannot properly create the storer for: [_TABLE_MAP] [group->/df_with_missing (Group) '',value-><class 'NoneType'>,format->None` during the triangulation step.

I have tried all versions made both before and after this post(from 0.8.1 to 1.1.4), but I get the same error in all. 
I attempted the solution @abigrassler suggested, but I was not able to pull from the repository, since I got the following error, suggesting that the repository is private: `Remote: Not Found fatal: repository 'https://github.com/lambdaloop/anipose/commit/4eeaa9a84da68f3dbffe3326ac455ca335e660c0/' not found`

@lambdaloop do you have any other suggestions as to how I could solve this?

I have attached my conda list and my configuration file.
[Test5_config.txt](https://github.com/user-attachments/files/16247220/Test5_config.txt)
[(anipose_clone) Conda list.txt](https://github.com/user-attachments/files/16247221/anipose_clone.Conda.list.txt)

I am aware that it is not the recommended python version, or Tensorflow(TF) version, but I have not been able to get anipose to analyze using a fresh environment in Python=3.7 TF=1.13.1, so I cloned this environment where I got the analysis-step to work. 

I appreciate any feedback and suggestions!

Best regards, 
Sol
