### ISSUE TITLE
label-2d problems

### ISSUE THREAD

**Issue by hanhanhan-kim** [lambdaloop/anipose#12]
Hello,
I ran the `anipose label-2d` on raw videos that are either `.mp4` or `.avi`. For both cases, the output labelled video is black, and no images can be seen. What might the issue be?
Thanks!

**Comment by hanhanhan-kim** [comment]
Solved: Turns out it was an `ffmpeg` issue for me. I downgraded from 4.0 to 3.4 in conda.

**Comment by lambdaloop** [comment]
Oh that's an interesting issue, thank you for documenting this! We'll have to mention this in the docs

**Comment by hanhanhan-kim** [comment]
Thank you for writing this code base! It's extremely useful :)
Out of curiosity, may I ask what your environment looks like? I feel like mine is always teetering on the edge of instability, haha

**Comment by DuanWei-fudan** [comment]
I got a key-error when I label-2d
_Labeling videos in 2D...
D:\DW\Anipose\2021-07-20-mouse-test\20210719
D:\DW\Anipose\2021-07-20-mouse-test\20210719\videos-labeled\rec-9-G1-20210719105659-camA.mp4
Traceback (most recent call last):
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '-'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\administrator\anaconda3\envs\anipose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Anaconda3\envs\anipose\Scripts\anipose.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\anipose\anipose.py", line 243, in label_2d
    label_videos_all(config)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\anipose\common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\anipose\common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\anipose\label_videos.py", line 160, in process_session
    visualize_labels(config, fname, vidname, out_fname)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\anipose\label_videos.py", line 96, in visualize_labels
    points = [(dlabs[bp]['x'], dlabs[bp]['y']) for bp in bodyparts]
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\anipose\label_videos.py", line 96, in <listcomp>
    points = [(dlabs[bp]['x'], dlabs[bp]['y']) for bp in bodyparts]
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\pandas\core\frame.py", line 2905, in __getitem__
    return self._getitem_multilevel(key)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\pandas\core\frame.py", line 2955, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\pandas\core\indexes\multi.py", line 2704, in get_loc
    loc = self._get_level_indexer(key, level=0)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\pandas\core\indexes\multi.py", line 2969, in _get_level_indexer
    code = self._get_loc_single_level_index(level_index, key)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\pandas\core\indexes\multi.py", line 2637, in _get_loc_single_level_index
    return level_index.get_loc(key)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: '-'_
How about that? How can I solve it?

**Comment by DuanWei-fudan** [comment]
Hello? Thank you in advance

**Comment by lambdaloop** [comment]
@DuanWei-fudan 
Hey, what does your `config.toml` look like? 
It seems that you have a "-" in there as a bodypart in your `scheme` variable, but that's not a bodypart?
