### ISSUE TITLE
Error in Calibration

### ISSUE THREAD

**Issue by ebtanana** [lambdaloop/anipose#123]
Hello,

I have began to use the ChArUco board for the calibration and have ran into an error regarding the output matrix of the detections:

100%|█████████████████████████████| 1447/1447 [00:48<00:00, 29.72it/s]
477 boards detected
C:\Users\ETV5\Documents\anipose_miles\raiden_0108\2023-01_08\calibration\calib_cam2.mp4
100%|█████████████████████████████| 5779/5779 [07:01<00:00, 13.70it/s]
5543 boards detected
C:\Users\ETV5\Documents\anipose_miles\raiden_0108\2023-01_08\calibration\calib_cam3.mp4
100%|█████████████████████████████| 5779/5779 [01:47<00:00, 53.53it/s]
948 boards detected
C:\Users\ETV5\Documents\anipose_miles\raiden_0108\2023-01_08\calibration\calib_cam4.mp4
100%|█████████████████████████████| 5779/5779 [01:53<00:00, 50.97it/s]
833 boards detected
defaultdict(<class 'int'>,
            {('1', '2'): 78,
             ('1', '4'): 2,
             ('2', '1'): 78,
             ('2', '3'): 101,
             ('2', '4'): 35,
             ('3', '2'): 101,
             ('4', '1'): 2,
             ('4', '2'): 35})
C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\numpy\core\fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\numpy\core\_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\Scripts\anipose.exe\__main__.py", line 7, in <module>
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\anipose\anipose.py", line 118, in calibrate    calibrate_all(config)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\anipose\common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\anipose\common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\anipose\calibrate.py", line 208, in process_session
    verbose=True)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\aniposelib\cameras.py", line 1565, in calibrate_rows
    rvecs, tvecs = get_initial_extrinsics(rtvecs, self.get_names())
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\aniposelib\utils.py", line 179, in get_initial_extrinsics
    extrinsics = compute_camera_matrices(rtvecs, pairs)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\aniposelib\utils.py", line 172, in compute_camera_matrices
    ext = get_transform(rtvecs, b, a)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\aniposelib\utils.py", line 78, in get_transform
    M_mean = mean_transform_robust(L, M_mean, error=0.1)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\aniposelib\utils.py", line 60, in mean_transform_robust
    return mean_transform(M_list_robust)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\aniposelib\utils.py", line 48, in mean_transform
    return make_M(rvec, tvec)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\aniposelib\utils.py", line 11, in make_M
    rotmat, _ = cv2.Rodrigues(rvec)
cv2.error: OpenCV(3.4.18) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\calibration.cpp:3233: error: (-2:Unspecified error) in function 'void __cdecl cv::Rodrigues(const class cv::_InputArray &,const class cv::_OutputArray &,const class cv::_OutputArray &)'
> Input matrix must be 1x3 or 3x1 for a rotation vector, or 3x3 for a rotation matrix:
>     'srcSz == Size(3, 1) || srcSz == Size(1, 3) || (srcSz == Size(1, 1) && src.channels() == 3) || srcSz == Size(3, 3)'
> where
>     'srcSz' is [1 x 4]

My current config file is below for anyone who can assist:

[calibration]
checkerboard / charuco / aruco
board_type = "charuco"

width and height of grid
board_size = [7,10]

number of bits in the markers, if aruco/charuco
board_marker_bits = 4

number of markers in dictionary, if aruco/charuco
board_marker_dict_number = 50

length of marker side
board_marker_length = 0.011 # m

If charuco or checkerboard, square side length
board_square_side_length = 0.015 # m

animal_calibration = true

fisheye = false

**Comment by LWitter** [comment]
One thing I notice is that your first calibration movie has a much lower frame count than the other three. Could that be your issue?
Also, I have a similar issue before ([issue 28](https://github.com/lambdaloop/anipose/issues/28)) which was due to a low number of overlapping boards between the movies.

**Comment by ebtanana** [comment]
@LWitter I thought that could be the issue, but I've ran this with lower boards detected (surprisingly), and it would just result in a massive error. It's weird because in that camera, when upside down it detects like 1000+ board but I believe I get the same error
