### ISSUE TITLE
Anipose Label-3D 'traitsui.toolkits'

### ISSUE THREAD

**Issue by ebtanana** [lambdaloop/anipose#125]
I'm using Anipose and I have been receiving an error from the function 'anipose label-3d' in which I receive the following error:

Traceback (most recent call last):
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\importlib_metadata\__init__.py", line 292, in __getitem__
    return next(iter(self.select(name=name)))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\Scripts\anipose.exe\__main__.py", line 7, in <module>
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\anipose\anipose.py", line 257, in label_3d
    from .label_videos_3d import label_videos_3d_all
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\anipose\label_videos_3d.py", line 3, in <module>
    from mayavi import mlab
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\mayavi\mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\mayavi\tools\camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\mayavi\tools\engine_manager.py", line 12, in <module>
    from mayavi.preferences.api import preference_manager
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\mayavi\preferences\api.py", line 4, in <module>
    from .preference_manager import preference_manager
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\mayavi\preferences\preference_manager.py", line 29, in <module>
    from traitsui.api import View, Group, Item
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\traitsui\api.py", line 256, in <module>
    from .editors.api import ArrayEditor
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\traitsui\editors\__init__.py", line 16, in <module>
    from .api import ArrayEditor
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\traitsui\editors\api.py", line 86, in <module>
    from .code_editor import CodeEditor
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\traitsui\editors\code_editor.py", line 21, in <module>
    class CodeEditor(EditorFactory):
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\traitsui\editors\code_editor.py", line 33, in CodeEditor
    mark_color = Color(0xECE9D8)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\traits\trait_factory.py", line 40, in __call__
    return self.maker_function(*args, **metadata)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\traitsui\toolkit_traits.py", line 43, in ColorTrait
    return toolkit().color_trait(*args, **traits)
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\traitsui\toolkit.py", line 110, in toolkit
    _toolkit = find_toolkit("traitsui.toolkits")
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\pyface\base_toolkit.py", line 285, in find_toolkit
    plugin for plugin in importlib_metadata.entry_points()[entry_point]
  File "C:\Users\ETV5\AppData\Local\anaconda3\envs\anipose\lib\site-packages\importlib_metadata\__init__.py", line 294, in __getitem__
    raise KeyError(name)
KeyError: 'traitsui.toolkits'

This is my conda list in case I'm missing a dependency:

# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
anipose                   1.0.1                    pypi_0    pypi
aniposelib                0.5.1                    pypi_0    pypi
apptools                  5.2.1                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
blas                      1.0                         mkl
brotli                    1.1.0                    pypi_0    pypi
ca-certificates           2023.12.12           haa95532_0
cachetools                5.3.2                    pypi_0    pypi
certifi                   2022.12.7        py37haa95532_0
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
configobj                 5.0.6            py37haa95532_1
cudatoolkit               11.2.2              h933977f_10    conda-forge
cudnn                     8.1.0.77             h3e0f4f4_0    conda-forge
curl                      8.5.0                he2ea4bf_0
cycler                    0.11.0                   pypi_0    pypi
deeplabcut                2.3.6                    pypi_0    pypi
dlclibrary                0.0.5                    pypi_0    pypi
envisage                  6.0.1              pyhd3eb1b0_0
expat                     2.5.0                hd77b12b_0
ffmpeg                    4.2.2                he774522_0
filelock                  3.12.2                   pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
flask                     2.2.5                    pypi_0    pypi
flask-compress            1.14                     pypi_0    pypi
flask-ipban               1.1.5                    pypi_0    pypi
flatbuffers               23.5.26                  pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
fsspec                    2023.1.0                 pypi_0    pypi
future                    0.18.3           py37haa95532_0
gast                      0.4.0                    pypi_0    pypi
google-auth               2.26.2                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.60.0                   pypi_0    pypi
h5py                      3.8.0                    pypi_0    pypi
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.6               h1756f20_1
huggingface-hub           0.16.4                   pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2
icu                       58.2                 ha925a31_3
idna                      3.6                      pypi_0    pypi
imageio                   2.31.2                   pypi_0    pypi
imageio-ffmpeg            0.4.9                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
itsdangerous              2.1.2                    pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_1
jsoncpp                   1.9.4                h59b6b97_3
keras                     2.10.0                   pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libclang                  16.0.6                   pypi_0    pypi
libcurl                   8.5.0                h86230a5_0
libdeflate                1.17                 h2bbff1b_1
libiconv                  1.16                 h2bbff1b_2
libnetcdf                 4.6.1                hf59b723_4
libpng                    1.6.39               h8cc25b3_0
libssh2                   1.10.0               hcd4344a_2
libtiff                   4.5.0                h8a3f274_0
libxml2                   2.9.14               h0ad7f3c_0
llvmlite                  0.39.1                   pypi_0    pypi
lz4-c                     1.8.1.2              h2fa13f4_0
markdown                  3.4.4                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mayavi                    4.8.1                    pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py37h2bbff1b_0
mkl_fft                   1.3.1            py37h277e83a_0
mkl_random                1.2.2            py37hf11a4ad_0
msgpack                   1.0.5                    pypi_0    pypi
msgpack-numpy             0.4.8                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numexpr                   2.8.6                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
numpy-base                1.21.5           py37hca35cd5_3
oauthlib                  3.2.2                    pypi_0    pypi
opencv-contrib-python     3.4.18.65                pypi_0    pypi
opencv-python             3.4.18.65                pypi_0    pypi
openssl                   1.1.1w               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
patsy                     0.5.6                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       22.3.1           py37haa95532_0
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.7                    pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pyface                    7.3.0            py37haa95532_1
pygments                  2.11.2             pyhd3eb1b0_0
pyparsing                 3.1.1                    pypi_0    pypi
pyqt                      5.9.2            py37hd77b12b_6
python                    3.7.16               h6244533_0
python-dateutil           2.8.2                    pypi_0    pypi
python-version            0.0.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.2                   pypi_0    pypi
qt                        5.9.7            vc14h73c81de_0
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.18.5                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scikit-video              1.1.11                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                65.6.3           py37haa95532_0
shapely                   2.0.2                    pypi_0    pypi
sip                       4.19.13          py37hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1    anaconda
sqlite                    3.41.2               h2bbff1b_0
statsmodels               0.13.5                   pypi_0    pypi
tables                    3.7.0                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.10.0                   pypi_0    pypi
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-intel          2.11.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
tensorpack                0.11                     pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
tf-slim                   1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
torch                     1.12.0                   pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
traits                    6.2.0            py37h2bbff1b_0
traitsui                  7.2.1              pyhd3eb1b0_0
typing-extensions         4.7.1                    pypi_0    pypi
urllib3                   2.0.7                    pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
vtk                       8.2.0           py37h1e53df8_200
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py37haa95532_0
wincertstore              0.2              py37haa95532_2
wrapt                     1.16.0                   pypi_0    pypi
wxpython                  4.0.4            py37ha925a31_0    anaconda
xz                        5.4.5                h8cc25b3_0
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zstd                      1.3.7                h508b16e_0

**Comment by Scottydoesntkno** [comment]
Ever find a solution?
