### ISSUE TITLE
triangulation error

### ISSUE THREAD

**Issue by hanhanhan-kim** [lambdaloop/anipose#13]
Hello @lambdaloop ,
I am trying to run `anipose triangulate` but I appear to be getting a shape error like so:
```
(anipose-2d-viz) hank-x299@hank-x299:/mnt/2TB/Dropbox/datasets/for_anipose/dalotiapose$ anipose triangulate
Triangulating points...
/mnt/2TB/Dropbox/datasets/for_anipose/dalotiapose/test_6_no_motor/pose-3d/dal_liom__2020_02_06_15_59_43.csv
Traceback (most recent call last):
  File "/home/hank-x299/anaconda3/envs/anipose-2d-viz/bin/anipose", line 11, in <module>
    load_entry_point('anipose', 'console_scripts', 'anipose')()
  File "/home/hank-x299/anaconda3/envs/anipose-2d-viz/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hank-x299/anaconda3/envs/anipose-2d-viz/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hank-x299/anaconda3/envs/anipose-2d-viz/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hank-x299/anaconda3/envs/anipose-2d-viz/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hank-x299/anaconda3/envs/anipose-2d-viz/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hank-x299/anaconda3/envs/anipose-2d-viz/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/hank-x299/anaconda3/envs/anipose-2d-viz/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hank-x299/src/anipose/anipose/anipose.py", line 158, in triangulate
    triangulate_all(config)
  File "/home/hank-x299/src/anipose/anipose/common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "/home/hank-x299/src/anipose/anipose/common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "/home/hank-x299/src/anipose/anipose/triangulate.py", line 328, in process_session
    fname_dict, output_fname)
  File "/home/hank-x299/src/anipose/anipose/triangulate.py", line 237, in triangulate
    points_3d = cgroup.triangulate(points_2d, progress=True)
  File "/home/hank-x299/src/calligator/calligator/cameras.py", line 470, in triangulate
    len(self.cameras), points.shape
AssertionError: Invalid points shape, first dim should be equal to number of cameras (4), but shape is (1, 8016, 2)
```
Why might my first dim not match my number of cameras? The output `calibration.toml` file from `anipose calibrate` is as follows:
```
[cam_0]
name = "18475997"
size = [ 720, 540,]
matrix = [ [ 1.579937897350622e-9, 0.0, 359.5,], [ 0.0, 1.579937897350622e-9, 269.5,], [ 0.0, 0.0, 1.0,],]
distortions = [ -3.144523897087529e-6, 0.0, 0.0, 0.0, 0.0,]
rotation = [ 0.00414603630815267, 0.1219035008662274, -0.2865174292114367,]
translation = [ 27691.78492496907, 18857.25662426044, -0.05080337727313677,]

[cam_1]
name = "19061101"
size = [ 720, 540,]
matrix = [ [ 3940085.308362053, 0.0, 359.5,], [ 0.0, 3940085.308362053, 269.5,], [ 0.0, 0.0, 1.0,],]
distortions = [ -2074.529286566875, 0.0, 0.0, 0.0, 0.0,]
rotation = [ 17557.08058349543, -737.7576224740999, -327.2018426416136,]
translation = [ 2016808012.038999, -253530721.0348125, 280339008.100099,]

[cam_2]
name = "19061600"
size = [ 720, 540,]
matrix = [ [ -166371.7609030413, 0.0, 359.5,], [ 0.0, -166371.7609030413, 269.5,], [ 0.0, 0.0, 1.0,],]
distortions = [ 26.6270212226631, 0.0, 0.0, 0.0, 0.0,]
rotation = [ 5.110329415919487, 3.386310472928838, -6.314679086461423,]
translation = [ 43310.79681988942, 47221.44031715184, 1046.281440359661,]

[cam_3]
name = "19061602"
size = [ 720, 540,]
matrix = [ [ 3477688.138059122, 0.0, 359.5,], [ 0.0, 3477688.138059122, 269.5,], [ 0.0, 0.0, 1.0,],]
distortions = [ -52.13839237435668, 0.0, 0.0, 0.0, 0.0,]
rotation = [ -3.878485957787288, 5.094652480771372, -14.79670715654272,]
translation = [ -99616.9443827019, -84179.57879928176, 9541.193737878069,]

[metadata]
adjusted = false
error = 1.312791890549888e+17
```

Thanks!

**Comment by hanhanhan-kim** [comment]
Solved: 
The solution was related to something you said in issue #11 . 

>For the calibration videos, Anipose expects them:
(1) to be recorded simultaneously from all cameras
(2) to have each group recorded at the same time to have the same filename, once the camera name is removed

A quirk of my set-up is that although everything is synced via an external trigger, the file name's time stamp begins once I toggle a setting specifying that I will be using an external trigger . . . I simply had to rename my files, so that aside from the camera name, everything was exactly identical. The resulting `calibration.toml` file now consists of much more reasonable values. 

If possible, may I perhaps request an assertion error so that `anipose calibrate` does not run, unless the vid file names are exactly identical, minus the cam names? 

Thank you again for your helpful tips and writing this code base!

**Comment by DuanWei-fudan** [comment]
hi ,I met a problem like this:
_c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\numpy\lib\function_base.py:1273: RuntimeWarning: invalid value encountered in subtract
  a = op(a[slice1], a[slice2])
c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\aniposelib\cameras.py:1320: RuntimeWarning: invalid value encountered in subtract
  lengths = np.linalg.norm(p3ds[:, a] - p3ds[:, b], axis=1)
c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\aniposelib\cameras.py:1337: RuntimeWarning: invalid value encountered in greater
  joint_lengths[joint_lengths > med+mad*5] = med
c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\scipy\optimize\_lsq\common.py:369: RuntimeWarning: invalid value encountered in greater_equal
  return np.all((x >= lb) & (x <= ub))
c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\scipy\optimize\_lsq\common.py:369: RuntimeWarning: invalid value encountered in less_equal
  return np.all((x >= lb) & (x <= ub))
Traceback (most recent call last):
  File "c:\users\administrator\anaconda3\envs\anipose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Anaconda3\envs\anipose\Scripts\anipose.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\anipose\anipose.py", line 158, in triangulate
    triangulate_all(config)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\anipose\common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\anipose\common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\anipose\triangulate.py", line 339, in process_session
    fname_dict, output_fname)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\anipose\triangulate.py", line 216, in triangulate
    verbose=True)
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\aniposelib\cameras.py", line 1048, in optim_points
    n_deriv_smooth))
  File "c:\users\administrator\anaconda3\envs\anipose\lib\site-packages\scipy\optimize\_lsq\least_squares.py", line 795, in least_squares
    raise ValueError("`x0` is infeasible.")
ValueError: `x0` is infeasible._

How about that?
