### ISSUE TITLE
anipose filter-3d issue

### ISSUE THREAD

**Issue by hanhanhan-kim** [lambdaloop/anipose#14]
Hello,

I'm having some issues trying to execute `anipose filter-3d`. I consistently get a `numpy` error like so:

```
(anipose-2d-viz) hank-x299@hank-x299:/mnt/2TB/Dropbox/datasets/for_anipose/dalotiapose$ anipose filter-3d
Filtering tracked points...
/mnt/2TB/Dropbox/datasets/for_anipose/dalotiapose/test_1_no_motor/pose-3d-filtered/dal_liom__2020_02_06_11_21.csv
/home/hank-x299/anaconda3/envs/anipose-2d-viz/lib/python3.6/site-packages/numpy/lib/function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
```

I am using `numpy==1.16.4`. My 2D-tracking after filtering looks good, and my `calibration.toml` file is like so:
```
[cam_0]
name = "18475997"
size = [ 720, 540,]
matrix = [ [ 9.638756622617622, 0.0, 359.5,], [ 0.0, 9.638756622617622, 269.5,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.002321125597023245, 0.0, 0.0, 0.0, 0.0,]
rotation = [ 0.07377960282678943, 0.00883013460354334, -0.04760874463639168,]
translation = [ -0.2786317828208055, 0.3293169341307745, -0.03600747822987863,]

[cam_1]
name = "19061101"
size = [ 720, 540,]
matrix = [ [ 24.96617363229602, 0.0, 359.5,], [ 0.0, 24.96617363229602, 269.5,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.0003751601954273957, 0.0, 0.0, 0.0, 0.0,]
rotation = [ -0.07387913606012508, 0.01903475208959475, 0.1710721036246948,]
translation = [ -1.384724062163185, 0.1546314401368329, 0.05040677950337349,]

[cam_2]
name = "19061600"
size = [ 720, 540,]
matrix = [ [ 9.670335210422285, 0.0, 359.5,], [ 0.0, 9.670335210422285, 269.5,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.003562620248271928, 0.0, 0.0, 0.0, 0.0,]
rotation = [ 0.1284161881272207, 0.003714826710541101, -0.1994563425933652,]
translation = [ -0.2258772873279897, 0.3692173507505997, -0.01727518616371634,]

[metadata]
adjusted = false
error = 1.931100687210916
```

My filter in the `config.toml` file consists of the default values included in the repo:
```
# Settings for a threshold filter
# Removes data outside threshold (probably errors in tracking), and interpolates
[filter]
enabled = true
medfilt = 13 # length of median filter
offset_threshold = 25 # offset from median filter to count as jump
score_threshold = 0.8 # score below which to count as bad
spline = true # interpolate using cubic spline instead of linear
```

Why might I be getting the above error? 
Thank you!

**Comment by hanhanhan-kim** [comment]
Update:
When I try with `numpy==1.17.2`, the error disappears when I run `anipose filter-3d`. When I then run `anipose label-3d-filter`, however, I get the following new error:
```
(anipose-3d) hank-x299@hank-x299:/mnt/2TB/Dropbox/datasets/for_anipose/dalotiapose$ anipose label-3d-filter
Labeling videos in 3D...
/mnt/2TB/Dropbox/datasets/for_anipose/dalotiapose/test_6_no_motor/videos-3d-filtered/dal_liom__2020_02_06_15_59.avi
Traceback (most recent call last):
  File "/home/hank-x299/anaconda3/envs/anipose-3d/bin/anipose", line 8, in <module>
    sys.exit(cli())
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/anipose/anipose.py", line 255, in label_3d_filter
    label_videos_3d_filtered_all(config)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/anipose/common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/anipose/common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/anipose/label_videos_3d.py", line 191, in process_session
    visualize_labels(config, fname, out_fname, params['fps'])
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/anipose/label_videos_3d.py", line 82, in visualize_labels
    low, high = np.percentile(all_points_flat[check], [5, 95], axis=0)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3707, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3826, in _quantile_unchecked
    interpolation=interpolation)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3405, in _ureduce
    r = func(a, **kwargs)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3941, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 189, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/home/hank-x299/anaconda3/envs/anipose-3d/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
```
I suspect there is something funny with my `.csv` in `pose-3d-filtered`? I've attached it [here](https://github.com/lambdaloop/anipose/files/4242451/pose-3d-filtered.zip).

Thank you!

**Comment by lambdaloop** [comment]
Hello @hanhanhan-kim ,

Thank you for filing this issue! I apologize that it took so long for me to get to it!

I'm not sure what the error is exactly with the 3D filter, but generally I suggest to constrained optimization filter. In the future (soon!), it will just become the default 3D filter.

For now, instead of enabling the 3D filter, just run triangulation as before and add parameters for constrained optimization as per this issue response: 
https://github.com/lambdaloop/anipose/issues/7#issuecomment-565284876

Let me know if that makes sense!

I apologize again for the confusing structure of the 3D filtering. I will rearrange Anipose to become more intuitive in the coming weeks!

**Comment by hanhanhan-kim** [comment]
Hi @lambdaloop ,
Thanks for getting back to me! I appreciate the fix--my 3d pose videos do look better, but still not great, hahaha--I imagine there might be some issues on my end . . . .
I look forward to seeing the upgrades and fixes you have planned for anipose! :)

**Comment by lambdaloop** [comment]
I think this has actually been resolved, so I'm closing it now
