### ISSUE TITLE
Could not run anipose analyze with the toml file

### ISSUE THREAD

**Issue by yiyangcrick** [lambdaloop/anipose#140]
Hi all,

I am currently trying to integrate frames from 4 cameras to have a 3d posture estimation of my animals. I have problems when trying to run the anipose analyze command, which gave me keyerror from the 'nesting' parameter.

The below is the config file that I use and the error message. I am running it on Windows Server 2019. 

project = "BRYE203c"
# path = "/nemo/lab/iacarusof/home/users/yangy1/anipose"
path = 'E:\anipose'
# model_folder = "/nemo/lab/iacarusof/home/shared/DeepLabCut/BRYE203c_4_cameras-YY-2024-06-14"
model_folder = 'Z:\home\shared\DeepLabCut\BRYE203c_4_cameras-YY-2024-06-14'

nesting = 0

video_extension = 'avi'

[pipeline]
videos_raw = "240524" # change this if you'd like to change name of "videos-raw" folder

[calibration]
# checkerboard / charuco / aruco
board_type = "charuco"
# width and height of grid, in squares
board_size = [6, 8]
# number of bits in the markers, if aruco/charuco
board_marker_bits = 6
# number of markers in dictionary, if aruco/charuco
board_marker_dict_number = 250
# length of marker side
board_marker_length = 15 # mm
# If charuco or checkerboard, square side length
board_square_side_length = 30 # mm

[manual_verification]
# true / false
manually_verify = true

animal_calibration = false
# calibration_init = 'calibration_init.toml'

[filter]
enabled = true
medfilt = 13
offset_threshold = 25
score_threshold = 0.8
spline = true

[labeling]
scheme = [
    ['Snout', 'Right_Ear'],
    ['Snout', 'Left_Ear'],
    ['Snout', 'Neck'],
    ['Neck', 'Shoulder'],
    ['Shoulder', 'Hip'],
    ['Hip', 'Tail_Base'],
    ['Tail_Base', 'Tail_End'],
    ['Left_Ear', 'Neck'],
    ['Right_Ear', 'Neck'],
    ['Left_Ear', 'Right_Ear'],
    ['Prey', 'Prey_Dup_bar'],
    ['Left_Screen', 'Right_Screen'],
    ['Left_Corridor', 'Right_Corridor']
]

[triangulation]
cam_regex = r'BRYE203c_\d{6}_(\w+?)\d+\.avi'

axes = [
    ["x", "Left_Corridor", "Right_Corridor"],
    ["z", "Prey", "Prey_Dup_bar"]
]
reference_point = "Left_Corridor"
cam_align = "TOP"

#[angles]
#1_CF = ["L1A", "L1B", "L1C"]
#L1_FTi = ["L1B", "L1C", "L1D"]
#L1_TiTa = ["L1C", "L1D", "L1E"]

#L2_CF = ["L2A", "L2B", "L2C"]
#L2_FTi = ["L2B", "L2C", "L2D"]
#L2_TiTa = ["L2C", "L2D", "L2E"]

#L3_CF = ["L3A", "L3B", "L3C"]
#L3_FTi = ["L3B", "L3C", "L3D"]
#L3_TiTa = ["L3C", "L3D", "L3E"]

#[cameras.A]
#offset = [224, 120, 832, 704]

#[cameras.B]
offset = [224, 230, 800, 700]

#[cameras.C]
offset = [160, 250, 864, 700]

(anipose) E:\anipose>anipose analyze
Analyzing videos...
Traceback (most recent call last):
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\Scripts\anipose.exe\__main__.py", line 7, in <module>
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\site-packages\anipose\anipose.py", line 142, in analyze
    pose_videos_all(config)
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\site-packages\anipose\common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "C:\Users\yangy1\AppData\Local\anaconda3\envs\anipose\lib\site-packages\anipose\common.py", line 120, in process_all
    nesting = config['nesting']
KeyError: 'nesting'

Does anyone what would cause this problem? 

Thanks!

Yi

**Comment by Sarahzzzzz** [comment]
Hi，have you solved this problem？I have the same issue ，thanks a lot!

**Comment by yiyangcrick** [comment]
> Hi，have you solved this problem？I have the same issue ，thanks a lot!

No, still struggling to get it to work
