### ISSUE TITLE
DLT algorithm needs at least 6 points

### ISSUE THREAD

**Issue by niccle27** [lambdaloop/anipose#19]
Hello!

i just came accross an issue:

**Describe the bug**
> DLT algorithm needs at least 6 points for pose estimation from 3D-2D point correspondences. (expected: 'count >= 6'), where

>     'count' is 5
> must be greater than or equal to
>     '6' is 6

**To Reproduce**
I just used anipose calibration. I did exactly the same operations for several other groups of videos while everything went smooth.

**Expected behavior**
getting the calibration.toml file

here is a full log of what i obtained:
```bash
Calibrating...
/home/imagedpt/Documents/CN/Projets/Pipeline_pose_estimation/Anipose/calibration
/home/imagedpt/Documents/CN/Projets/Pipeline_pose_estimation/Anipose/calibration/calibration.toml
/home/imagedpt/Documents/CN/Projets/Pipeline_pose_estimation/Anipose/calibration/calib5_bigpat_30fps_cam11.avi
100%|███████████████████████████████| 937/937 [02:04<00:00,  7.55it/s]
306 boards detected
/home/imagedpt/Documents/CN/Projets/Pipeline_pose_estimation/Anipose/calibration/calib5_bigpat_30fps_cam12.avi
100%|███████████████████████████████| 937/937 [03:43<00:00,  4.19it/s]
518 boards detected
/home/imagedpt/Documents/CN/Projets/Pipeline_pose_estimation/Anipose/calibration/calib5_bigpat_30fps_cam5.avi
100%|███████████████████████████████| 937/937 [02:42<00:00,  5.78it/s]
870 boards detected
/home/imagedpt/Documents/CN/Projets/Pipeline_pose_estimation/Anipose/calibration/calib5_bigpat_30fps_cam8.avi
100%|███████████████████████████████| 937/937 [02:21<00:00,  6.61it/s]
902 boards detected
Traceback (most recent call last):
  File "/home/imagedpt/.virtualenvs/anipose_test/bin/anipose", line 8, in <module>
    sys.exit(cli())
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/anipose/anipose.py", line 115, in calibrate
    calibrate_all(config)
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/anipose/common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/anipose/common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/anipose/calibrate.py", line 186, in process_session
    n_samp_iter=100, n_samp_full=2000)
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/calligator/cameras.py", line 1551, in calibrate_rows
    all_rows[i] = board.estimate_pose_rows(cam, row)
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/calligator/boards.py", line 343, in estimate_pose_rows
    row['ids'])
  File "/home/imagedpt/.virtualenvs/anipose_test/lib/python3.6/site-packages/calligator/boards.py", line 504, in estimate_pose_points
    reprojectionError=30)
cv2.error: OpenCV(3.4.9) /io/opencv/modules/calib3d/src/calibration.cpp:1097: error: (-2:Unspecified error) in function 'void cvFindExtrinsicCameraParams2(const CvMat*, const CvMat*, const CvMat*, const CvMat*, CvMat*, CvMat*, int)'
> DLT algorithm needs at least 6 points for pose estimation from 3D-2D point correspondences. (expected: 'count >= 6'), where
>     'count' is 5
> must be greater than or equal to
>     '6' is 6
(anipose_test) 
```
i'm using this configuration : 
```toml
[calibration]
# checkerboard / charuco / aruco
board_type = "checkerboard"

# width and height of grid
board_size = [9, 6]

# number of bits in the markers, if aruco/charuco
# board_marker_bits = 4

# number of markers in dictionary, if aruco/charuco
# board_marker_dict_number = 50

# length of marker side
# board_marker_length = 33 # mm

# If aruco, length of marker separation
# board_marker_separation_length = 1 # mm

# If charuco or checkerboard, square side length
board_square_side_length = 33 # mm
animal_calibration = false
fisheye = false

[triangulation]
triangulate = true
# cam_regex = '-cam([1-12])'
cam_regex = 'cam([0-9]*)'
ransac = true
optim = true
constraints = [
   ["base", "MCP1"], ["MCP1", "PIP1"], ["PIP1", "tip1"],
   ["base", "MCP2"], ["MCP2", "PIP2"], ["PIP2", "DIP2"], ["DIP2", "tip2"],
   ["base", "MCP3"], ["MCP3", "PIP3"], ["PIP3", "DIP3"], ["DIP3", "tip3"],
   ["base", "MCP4"], ["MCP4", "PIP4"], ["PIP4", "DIP4"], ["DIP4", "tip4"],
   ["base", "MCP5"], ["MCP5", "PIP5"], ["PIP5", "DIP5"], ["DIP5", "tip5"]
]
scale_smooth = 25
scale_length = 10
scale_length_weak = 2
reproj_error_threshold = 3
score_threshold = 0.6
n_deriv_smooth = 2
```
As the video i'm using contains faces of people that i cannot provide, i won't be able to send the videos used... though i can provide the pickle file : https://we.tl/t-RbrtQPrGcE

Once again, thank you a lot for you work,

**Comment by lambdaloop** [comment]
Thank you for this detailed issue!!

With the provided pickle file, I was able to reproduce it. I'm still not sure what's happening, but it seems that in rare cases, all the points are still present but the OpenCV function errors when running the solvePnPRansac function to estimate the checkerboard pose. I suspect it's a bug in OpenCV. 

For now, I just caught the error and threw a warning when this happens, so that it's obvious if it too many boards are thrown out this way (in your case, only 10 detected boards, so a very small fraction). This is commit https://github.com/lambdaloop/anipose-lib/commit/579d04081ac48e323768188875c947d5cc596ddc .

If you update to anipose-lib v0.3.6, the issue should be now fixed

**Comment by niccle27** [comment]
Hello @lambdaloop 

Thank you a lot, this fixed my issue.
