### ISSUE TITLE
Anipose analyze has ImportError 

### ISSUE THREAD

**Issue by ijhua** [lambdaloop/anipose#22]
**Describe the bug**
When I run `anipose analyze` I get: ImportError: cannot import name 'aruco'
Installing opencv-python~=3.4 and opencv-contrib-python~=3.4doesn't do anything because it's already installed. Uninstalling and reinstalling does not work either.

**To Reproduce**
1. Install DeepLabCut and anipose in a new conda environment
2. Run `anipose analyze`

**Expected behavior**
It's expected to analyze the videos based on the config.toml file. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
Full traceback:
```
anipose analyze
Traceback (most recent call last):
  File "/home/ml/anaconda3/envs/anipose/bin/anipose", line 8, in <module>
    sys.exit(cli())
  File "/home/ml/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ml/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ml/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ml/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ml/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml/.local/lib/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ml/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ml/anaconda3/envs/anipose/lib/python3.6/site-packages/anipose/anipose.py", line 135, in analyze
    from .pose_videos import pose_videos_all
  File "/home/ml/anaconda3/envs/anipose/lib/python3.6/site-packages/anipose/pose_videos.py", line 11, in <module>
    from .common import natural_keys, make_process_fun
  File "/home/ml/anaconda3/envs/anipose/lib/python3.6/site-packages/anipose/common.py", line 10, in <module>
    from aniposelib.boards import CharucoBoard, Checkerboard
  File "/home/ml/anaconda3/envs/anipose/lib/python3.6/site-packages/aniposelib/__init__.py", line 6, in <module>
    from . import boards, cameras, utils
  File "/home/ml/anaconda3/envs/anipose/lib/python3.6/site-packages/aniposelib/boards.py", line 2, in <module>
    from cv2 import aruco
ImportError: cannot import name 'aruco'
```

**Comment by lambdaloop** [comment]
Hi @ijhua ,

Seems like it may be some issue with opencv-python and opencv-contrib-python conflicting. 
In particular see this issue: https://github.com/lambdaloop/aniposelib/issues/2
..along with the stackoverflow post pointed out: https://stackoverflow.com/questions/45972357/python-opencv-aruco-no-module-named-cv2-aruco

It seems that you did try to uninstall and reinstall but it didn't fix it. Could you try uninstalling both opencv-python and opencv-contrib-python and then installing only opencv-contrib-python, if you haven't already? 

Alternatively, could it be that you're not installing in the right environment..?
