### ISSUE TITLE
anipose calibrate - error: input matrix must be 1x3, 3x1 or 3x3 in function cvRodigrues2

### ISSUE THREAD

**Issue by LWitter** [lambdaloop/anipose#28]
**Describe the bug**
When trying 'anipose calibrate' on my movies I get the error message 'input matrix must be 1x3, 3x1 or 3x3 in function cvRodigrues2'.
I use three calibration movies cropped from one camera view. Two views are cropped and flipped since they're via mirrors, the center is only cropped.

I have the feeling this is an opencv version issue, but I'm really not sure.

Another issue is the low number of detected boards. I will take new movies with more boards, but I hope to first solve this issue. (Except of course when this is potentially an issue of low number of boars)

**Error:**
```
(DLC-GPU) D:\DLC\Trial_Loes_mirrors>anipose calibrate
Calibrating...
D:\DLC\Trial_Loes_mirrors\experiment 200526
D:\DLC\Trial_Loes_mirrors\experiment 200526\calibration\calibration.toml
defaultdict(<class 'int'>,
            {('A', 'B'): 54,
             ('B', 'A'): 54,
             ('B', 'C'): 73,
             ('C', 'B'): 73})
c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\numpy\core\fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\DLC-GPU\Scripts\anipose.exe\__main__.py",
line 7, in <module>
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\click\core.py",
line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\click\core.py",
line 782, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\click\core.py",
line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\click\core.py",
line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\click\core.py",
line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\click\core.py",
line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\anipose\anipose.py", line 115, in calibrate
    calibrate_all(config)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\anipose\common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\anipose\common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\anipose\calibrate.py", line 187, in process_session
    verbose=True)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\aniposelib\cameras.py", line 1560, in calibrate_rows
    rvecs, tvecs = get_initial_extrinsics(rtvecs)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\aniposelib\utils.py", line 174, in get_initial_extrinsics
    extrinsics = compute_camera_matrices(rtvecs, pairs)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\aniposelib\utils.py", line 167, in compute_camera_matrices
    ext = get_transform(rtvecs, b, a)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\aniposelib\utils.py", line 78, in get_transform
    M_mean = mean_transform_robust(L, M_mean, error=0.1)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\aniposelib\utils.py", line 60, in mean_transform_robust
    return mean_transform(M_list_robust)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\aniposelib\utils.py", line 48, in mean_transform
    return make_M(rvec, tvec)
  File "c:\programdata\anaconda3\envs\dlc-gpu\lib\site-packages\aniposelib\utils.py", line 11, in make_M
    rotmat, _ = cv2.Rodrigues(rvec)
cv2.error: OpenCV(3.4.9) C:\projects\opencv-python\opencv\modules\calib3d\src\calibration.cpp:292: error: (-201:Incorrect size of input array) Input matrix must
 be 1x3, 3x1 or 3x3 in function 'cvRodrigues2'
```

**Desktop (please complete the following information):**
 - OS: Win7 (SP1) 64bits
 - ipython 7.13.0
 - conda 4.8.2
 - opencv 3.4.9
 - anipose 0.8.1

 - Xeon W2123
 - 32 GB 
 - RTX2080Ti

**Comment by sebastian-ruiz** [comment]
I am running into the same error. I followed the installation guide on the readthedocs and also on anipose==0.8.0 I get the same error.

**Comment by lambdaloop** [comment]
Hello @LWitter and @sebastian-ruiz , could it be that you both have low number of boards? 
I think it's failing at setting up an initalization.

Could either of you share the "detections.pickle" file generated within your calibration folder? It would help me reproduce this issue.

**Comment by LWitter** [comment]
My apologies for getting back so late to this. This issue has moved to the backburner a bit I have to admit. Next two weeks I'll be off for holidays, so also not working on it then.

First thought on this: Could very well be the case that too few boards are detected. We try detection via a mirror and that turns out to be non-trivial. In other trials I had the direct error of 'not enough boards detected' (paraphrasing here).

How many boards (mutual detections) would you need for the software to work? I do have to note that I have three views, but a board can only be seen on two simultaneous views. It will be the backside of the other view. Also, two views can never see the same board at the same time. Would that be an issue?

Again many thanks for getting back, and apologies for delaying this.

**Comment by sebastian-ruiz** [comment]
I think I had the problem indeed because of too few boards.
