### ISSUE TITLE
Error during calibration

### ISSUE THREAD

**Issue by KonradDanielewski** [lambdaloop/anipose#3]
Hi,

when using anipose calibrate I get following error. "detections.pickle" file is created in calibration folder. When I use `anipose label-3d` after this it shows message "Labeling videos in 3D..." but nothing happens. Nothing is created and there is no error message.

`(dlc-windowsGPUclone) D:\Anipose\Test>anipose calibrate
Calibrating...
D:\Anipose\Test\Iteration1\calibration\calibration.toml
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPUclone\Scripts\anipose.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\anipose\anipose.py", line 105, in calibrate
    calibrate_all(config)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\anipose\common.py", line 165, in fun
    return process_all(config, process_session, **args)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\anipose\common.py", line 150, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\anipose\calibrate.py", line 182, in process_session
    n_samp_iter=100, n_samp_full=2000)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\calligator\cameras.py", line 1544, in calibrate_rows
    all_rows[i] = board.estimate_pose_rows(cam, row)
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\calligator\boards.py", line 333, in estimate_pose_rows
    row['ids'])
  File "c:\programdata\anaconda3\envs\dlc-windowsgpuclone\lib\site-packages\calligator\boards.py", line 611, in estimate_pose_points
    corners, ids, self.board, K, D)
TypeError: Required argument 'rvec' (pos 6) not found`

**Comment by lambdaloop** [comment]
Huh, that's odd. Could you share with me some example calibration videos so that I can try to reproduce this? You can email them to me if you'd prefer sharing them privately.

**Comment by KonradDanielewski** [comment]
Hello, I've put the whole calibration folder here, can also put the config file if it will be helpful. Do you think it might be because calibration info in config is wrong, or the sync is bad? https://drive.google.com/folderview?id=1kEVyL8a09cnoPEedE_op11mMeuBzp2D6

**Comment by lambdaloop** [comment]
Hi @KonradDanielewski,

I tried calibrating on my setup, and it seems to work. I suspect that there is an issue in the released version of anipose that I fixed since. I have updated anipose on pip (now to version 0.6.0).

Could you update and try again?

For reference, I needed to delete the "detections.pickle" and regenerate a new one for it to work properly. Here are the calibration.toml and detection.pickle files that I got. I also included the config.toml file that I used to generate these:
https://drive.google.com/open?id=14Y1mt_6PftRj9hkbU2PGfBp3bJ_G26wL

**Comment by KonradDanielewski** [comment]
I updated using pip, deleted the detections.pickle, but I get the same error. I will try to redo the whole env and try again this evening. 

As for now, I updated the folder on google drive, it now contains the config I used, calibration videos and videos I wanted to label-3d. 

If you have any general advise on what I can try and do, it'd be great.

**Comment by lambdaloop** [comment]
Hi @KonradDanielewski ,
I reproduced your error!
Turns out that I implicitly assume opencv-contrib of version 3, but I think you have version 4 installed.

Try running this: 
`pip install opencv-contrib-python~=3.4`

**Comment by KonradDanielewski** [comment]
Hello, this solved it. Calibration works now. Thank you
