### ISSUE TITLE
Calibrating error.

### ISSUE THREAD

**Issue by F2AGLAXY** [lambdaloop/anipose#60]
Good afternoon,

I am learning to use anipose to analyze videos. I tried to calibrate using the calibration video in the demo file you shared. But it showed the error below. How to solve this problem? Looking forward to hearing from you. 

Thanks in advance!

(py37) D:\anipose-test\hand-demo-unfilled>anipose calibrate
Calibrating...
D:\anipose-test\hand-demo-unfilled\2019-08-02
D:\anipose-test\hand-demo-unfilled\2019-08-02\calibration\calibration.toml
D:\anipose-test\hand-demo-unfilled\2019-08-02\calibration\calib-charuco-camA.MOV
100%|█████████████████████████████| 5274/5274 [03:27<00:00, 25.42it/s]
5274 boards detected
D:\anipose-test\hand-demo-unfilled\2019-08-02\calibration\calib-charuco-camB.MOV
100%|█████████████████████████████| 5264/5264 [03:32<00:00, 24.80it/s]
4986 boards detected
D:\anipose-test\hand-demo-unfilled\2019-08-02\calibration\calib-charuco-camC.MOV
100%|█████████████████████████████| 5265/5265 [03:13<00:00, 27.26it/s]
4724 boards detected
defaultdict(<class 'int'>, {('A', 'B'): 4937, ('B', 'A'): 4937})
Traceback (most recent call last):
  File "d:\anaconda3\envs\py37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\envs\py37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\py37\Scripts\anipose.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\py37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\envs\py37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\envs\py37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\py37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\envs\py37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3\envs\py37\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "d:\anaconda3\envs\py37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3\envs\py37\lib\site-packages\anipose\anipose.py", line 116, in calibrate
    calibrate_all(config)
  File "d:\anaconda3\envs\py37\lib\site-packages\anipose\common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "d:\anaconda3\envs\py37\lib\site-packages\anipose\common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "d:\anaconda3\envs\py37\lib\site-packages\anipose\calibrate.py", line 203, in process_session
    verbose=True)
  File "d:\anaconda3\envs\py37\lib\site-packages\aniposelib\cameras.py", line 1563, in calibrate_rows
    rvecs, tvecs = get_initial_extrinsics(rtvecs)
  File "d:\anaconda3\envs\py37\lib\site-packages\aniposelib\utils.py", line 173, in get_initial_extrinsics
    pairs = find_calibration_pairs(graph, source=0)
  File "d:\anaconda3\envs\py37\lib\site-packages\aniposelib\utils.py", line 156, in find_calibration_pairs
    for new in graph[item]:
TypeError: 'NoneType' object is not subscriptable

**Comment by shhmon** [comment]
Seems like the same problem as #51 and #48, still haven't gotten around this problem with my project. I've tried:

* rolling back to anipose `0.8.1` and aniposelib `0.3.7`
* rolling back numba to `0.50.1`
* cutting the videos to every x-th frame as suggested in #48 
* cutting the videos to only include frames in which the board is clearly visible
* using only two/three of my four cameras with best board detection
* all possible combinations of everything above

Seems like it's out of my hands now, just waiting for fixes

**Comment by F2AGLAXY** [comment]
Hi,
Rolling back to anipose 0.8.1 and aniposelib 0.3.7 can work,
Maybe you can try to upgrade or downgrade the version of other packages to check...
