### ISSUE TITLE
anipose label-3d (ModuleNotFoundError: No module named 'vtkCommonCorePython')

### ISSUE THREAD

**Issue by roouit** [lambdaloop/anipose#61]
Hi,

I've been able to analyze, filter, calibrate and triangulate my data, but I'm unable to generate 3D labels and I'm running to following error:

```
(anipose) E:\Tiedostoja\Gradu\dlc_anipose\anipose_data>anipose label-3d
Traceback (most recent call last):
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\vtkmodules\vtkCo
mmonCore.py", line 5, in <module>
    from .vtkCommonCorePython import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\roope\anaconda3\envs\anipose\lib\runpy.py", line 193, in _run_m
odule_as_main
    "__main__", mod_spec)
  File "c:\users\roope\anaconda3\envs\anipose\lib\runpy.py", line 85, in _run_co
de
    exec(code, run_globals)
  File "C:\Users\roope\anaconda3\envs\anipose\Scripts\anipose.exe\__main__.py",
line 7, in <module>
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\click\core.py",
line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\click\core.py",
line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\click\core.py",
line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\click\core.py",
line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\click\core.py",
line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\click\decorators
.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\click\core.py",
line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\anipose\anipose.
py", line 255, in label_3d
    from .label_videos_3d import label_videos_3d_all
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\anipose\label_vi
deos_3d.py", line 3, in <module>
    from mayavi import mlab
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\mayavi\mlab.py",
 line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\mayavi\tools\cam
era.py", line 24, in <module>
    from .engine_manager import get_engine
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\mayavi\tools\eng
ine_manager.py", line 13, in <module>
    from mayavi.core.registry import registry
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\mayavi\core\regi
stry.py", line 16, in <module>
    from mayavi.core.metadata import Metadata, import_symbol
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\mayavi\core\meta
data.py", line 11, in <module>
    from mayavi.core.pipeline_info import PipelineInfo
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\mayavi\core\pipe
line_info.py", line 12, in <module>
    from .utils import get_tvtk_dataset_name
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\mayavi\core\util
s.py", line 2, in <module>
    import vtk
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\vtk.py", line 32
, in <module>
    all_spec.loader.exec_module(all_m)
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\vtkmodules\all.p
y", line 7, in <module>
    from .vtkCommonCore import *
  File "c:\users\roope\anaconda3\envs\anipose\lib\site-packages\vtkmodules\vtkCo
mmonCore.py", line 9, in <module>
    from vtkCommonCorePython import *
ModuleNotFoundError: No module named 'vtkCommonCorePython'
```
Here is a list of installed packages in my env:
```
# Name                    Version                   Build  Channe
_tflow_select             2.1.0                       gpu
absl-py                   0.12.0           py37haa95532_0
anipose                   0.9.0                    pypi_0    pypi
aniposelib                0.4.1                    pypi_0    pypi
apptools                  5.1.0              pyhd3eb1b0_0
astor                     0.8.1            py37haa95532_0
backcall                  0.2.0                    pypi_0    pypi
bayesian-optimization     1.2.0                    pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2021.4.13            haa95532_1
cached-property           1.5.2                      py_0
certifi                   2020.12.5        py37haa95532_0
chardet                   4.0.0                    pypi_0    pypi
click                     8.0.1                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
configobj                 5.0.6            py37haa95532_1
coverage                  5.5              py37h2bbff1b_2
cudatoolkit               10.0.130                      0
cudnn                     7.6.5                cuda10.0_0
curl                      7.71.1               h2a8f88b_1
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.23          py37hd77b12b_0
decorator                 4.4.2                    pypi_0    pypi
deeplabcut                2.1.8.2                  pypi_0    pypi
easydict                  1.9                      pypi_0    pypi
envisage                  6.0.0              pyhd3eb1b0_0
expat                     2.4.1                h6c2663c_2
ffmpeg                    4.2.2                he774522_0
filterpy                  1.4.5                    pypi_0    pypi
freetype                  2.10.4               hd328e21_0
future                    0.18.2                   py37_1
gast                      0.4.0                      py_0
grpcio                    1.36.1           py37hc60d5dd_1
h5py                      2.10.0                   pypi_0    pypi
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.6               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imageio-ffmpeg            0.4.4                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        3.10.0           py37haa95532_0
importlib-resources       5.1.4                    pypi_0    pypi
intel-openmp              2021.2.0                 pypi_0    pypi
ipython                   7.23.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9b                   hb83a4c4_2
jsoncpp                   1.9.4                h59b6b97_2
keras-applications        1.0.8                      py_1
keras-preprocessing       1.1.2              pyhd3eb1b0_0
kiwisolver                1.3.1                    pypi_0    pypi
krb5                      1.18.2               hc04afaa_0
libcurl                   7.71.1               h2a8f88b_1
libiconv                  1.15                 h1df5818_7
libnetcdf                 4.6.1                hf59b723_3
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.14.0               h23ce68f_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.1.0                h56a325e_0
libxml2                   2.9.10               hb89e7f3_3
llvmlite                  0.33.0                   pypi_0    pypi
lz4-c                     1.8.1.2              h2fa13f4_0
markdown                  3.3.4            py37haa95532_0
matplotlib                3.0.3                    pypi_0    pypi
matplotlib-inline         0.1.2                    pypi_0    pypi
mayavi                    4.7.1            py37h11817fe_2
mkl                       2021.2.0           haa95532_296
mkl-service               2.3.0            py37h2bbff1b_1
mkl_fft                   1.3.0            py37h277e83a_2
mkl_random                1.2.1            py37hf11a4ad_2
mock                      4.0.3              pyhd3eb1b0_0
moviepy                   1.0.1                    pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
msgpack-numpy             0.4.7.1                  pypi_0    pypi
networkx                  2.5.1                    pypi_0    pypi
numba                     0.50.1                   pypi_0    pypi
numexpr                   2.7.3                    pypi_0    pypi
numpy                     1.16.4                   pypi_0    pypi
opencv-contrib-python     3.4.14.51                pypi_0    pypi
opencv-python             3.4.14.51                pypi_0    pypi
opencv-python-headless    3.4.9.33                 pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0
pandas                    1.1.5                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
patsy                     0.5.1                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.2.0                    pypi_0    pypi
pip                       21.1.1           py37haa95532_0
proglog                   0.1.9                    pypi_0    pypi
prompt-toolkit            3.0.18                   pypi_0    pypi
protobuf                  3.14.0           py37hd77b12b_1
psutil                    5.8.0                    pypi_0    pypi
pyface                    7.3.0            py37haa95532_1
pygments                  2.9.0              pyhd3eb1b0_0
pyparsing                 2.4.7                    pypi_0    pypi
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
python                    3.7.10               h6244533_0
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.1.0                   pypi_0    pypi
qt                        5.9.7            vc14h73c81de_0
requests                  2.25.1                   pypi_0    pypi
ruamel-yaml               0.17.4                   pypi_0    pypi
ruamel-yaml-clib          0.2.2                    pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scikit-video              1.1.11                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                52.0.0           py37haa95532_0
shapely                   1.7.1                    pypi_0    pypi
sip                       4.19.8           py37h6538335_0
six                       1.15.0           py37haa95532_0
sqlite                    3.35.4               h2bbff1b_0
statsmodels               0.12.2                   pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
tbb                       2021.2.0             h59b6b97_0
tensorboard               1.13.1           py37h33f27b4_0
tensorflow                1.13.1          gpu_py37h83e5d6a_0
tensorflow-base           1.13.1          gpu_py37h871c8ca_0
tensorflow-estimator      1.13.0                     py_0
tensorflow-gpu            1.13.1               h0d30ee6_0
tensorpack                0.9.8                    pypi_0    pypi
termcolor                 1.1.0            py37haa95532_1
threadpoolctl             2.1.0                    pypi_0    pypi
tifffile                  2021.4.8                 pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tqdm                      4.61.0                   pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
traits                    6.2.0            py37h2bbff1b_0
traitsui                  7.1.1              pyhd3eb1b0_0
typing_extensions         3.7.4.3            pyha847dfd_0
urllib3                   1.26.5                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
vtk                       8.2.0           py37h1e53df8_200
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  1.0.1              pyhd3eb1b0_0
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py37_0
wxpython                  4.1.1                    pypi_0    pypi
xz                        5.2.5                h62dcd97_0
zipp                      3.4.1              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.3.7                h508b16e_0
```
I haven't been able to figure this out by myself so any help would be greatly appreciated!

**Comment by roouit** [comment]
> 
> 
> I have been having the same problem. Were you able to fix this?

Unfortunately not.

**Comment by osskar12** [comment]
I am having the same issue. Help would be very welcome.
Running Ubuntu 18.02

**Comment by osskar12** [comment]
Solved it! 
Installing the newest vtk version 9.01 from conda-forge via 
`conda install -c conda-forge vtk`
did it for me

**Comment by LWitter** [comment]
I can't seem to install version 9.01
conda install -c conda-forge vtk installed version 8.2.0. Forcing version 9.01 doesn't work and throws an error.
