### ISSUE TITLE
OSError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by 0tist** [lambdaloop/anipose#68]
Trying to use `anipose label-3d'

OS: Ubuntu 20.04
anipose version: 0.8.1
aniposelib version: 0.3.7

```
Labeling videos in 3D...
/media/arnablab/VAULT/HotCold/Anipose_videos/experiment-omg/trial-1/videos-3d/processed_.mp4
  0%|                                        | 0/2000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/skvideo/io/abstract.py", line 514, in writeFrame
    self._proc.stdin.write(vid.tostring())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arnablab/anaconda3/envs/ANIPOSE/bin/anipose", line 8, in <module>
    sys.exit(cli())
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/anipose/anipose.py", line 248, in label_3d
    label_videos_3d_all(config)
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/anipose/common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/anipose/common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/anipose/label_videos_3d.py", line 197, in process_session
    visualize_labels(config, fname, out_fname, params['fps'])
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/anipose/label_videos_3d.py", line 147, in visualize_labels
    writer.writeFrame(img)
  File "/home/arnablab/anaconda3/envs/ANIPOSE/lib/python3.7/site-packages/skvideo/io/abstract.py", line 519, in writeFrame
    raise IOError(msg)
OSError: [Errno 32] Broken pipe

FFMPEG COMMAND:
/home/arnablab/anaconda3/bin/ffmpeg -y -framerate 60.0 -f rawvideo -pix_fmt rgb24 -s 500x500 -i - -vcodec h264 -qp 28 -pix_fmt yuv420p /media/arnablab/VAULT/HotCold/Anipose_videos/experiment-omg/trial-1/videos-3d/processed_.mp4

FFMPEG STDERR OUTPUT:

**Comment by 0tist** [comment]
installed the environment again and installed anipose==0.8.1 and aniposelib==0.3.7 works fine, but still curious about it, maybe someone can help?
