### ISSUE TITLE
calibration error in hand demo

### ISSUE THREAD

**Issue by JingwenLiUCSD** [lambdaloop/anipose#71]
I ran anipose calibration on the hand demo, and got this error:

Calibrating...
Z:\DLC - Marmo Tracking\Calibration\hand demo\hand-demo-unfilled\2019-08-02
Z:\DLC - Marmo Tracking\Calibration\hand demo\hand-demo-unfilled\2019-08-02\calibration\calibration.toml
Z:\DLC - Marmo Tracking\Calibration\hand demo\hand-demo-unfilled\2019-08-02\calibration\calib-charuco-camA.MOV
100%|█████████████████████████████| 5274/5274 [02:21<00:00, 37.16it/s]
5274 boards detected
Z:\DLC - Marmo Tracking\Calibration\hand demo\hand-demo-unfilled\2019-08-02\calibration\calib-charuco-camB.MOV
100%|█████████████████████████████| 5264/5264 [02:28<00:00, 35.49it/s]
4986 boards detected
Z:\DLC - Marmo Tracking\Calibration\hand demo\hand-demo-unfilled\2019-08-02\calibration\calib-charuco-camC.MOV
100%|█████████████████████████████| 5265/5265 [02:14<00:00, 39.13it/s]
4724 boards detected
defaultdict(<class 'int'>, {('A', 'B'): 4937, ('B', 'A'): 4937})
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\Scripts\anipose.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\anipose\anipose.py", line 116, in calibrate
    calibrate_all(config)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\anipose\common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\anipose\common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\anipose\calibrate.py", line 203, in process_session
    verbose=True)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\aniposelib\cameras.py", line 1565, in calibrate_rows
    rvecs, tvecs = get_initial_extrinsics(rtvecs, self.get_names())
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\aniposelib\utils.py", line 176, in get_initial_extrinsics
    graph = get_calibration_graph(rtvecs, cam_names)
  File "C:\ProgramData\Anaconda3\envs\anipose-gpu\lib\site-packages\aniposelib\utils.py", line 122, in get_calibration_graph
    for k,v in components.items():
RuntimeError: dictionary changed size during iteration

**Comment by lambdaloop** [comment]
Hi @JingwenLiUCSD 

I think I fixed this issue recently. Could you try to upgrade aniposelib to 0.4.3 and see whether it resolves the issue?

**Comment by JingwenLiUCSD** [comment]
Yes, it solves the problem! Thank you!

Jingwen

**Comment by lambdaloop** [comment]
Great! I'll close this issue then
