### ISSUE TITLE
anipose label-3d (ImportError: DLL load failed: The specified module could not be found.)

### ISSUE THREAD

**Issue by nini-matteo** [lambdaloop/anipose#72]
Hi,

I'm trying to test the anipose tutorial  with "hand-demo-dlc" and  "hand-demo-unfilled" folders.
I'm currently using Windows 10 Education Version 21H1.
When I try to launch "anipose label-3d" it shows the error:

```
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
Traceback (most recent call last):
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\vtkmodules\vtkCommonCore.py", line 5, in <module>
    from .vtkCommonCorePython import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\nini\Anaconda3\envs\dlc\Scripts\anipose.exe\__main__.py", line 7, in <module>
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\anipose\anipose.py", line 257, in label_3d
    from .label_videos_3d import label_videos_3d_all
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\anipose\label_videos_3d.py", line 3, in <module>
    from mayavi import mlab
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\mayavi\mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\mayavi\tools\camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\mayavi\tools\engine_manager.py", line 13, in <module>
    from mayavi.core.registry import registry
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\mayavi\core\registry.py", line 16, in <module>
    from mayavi.core.metadata import Metadata, import_symbol
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\mayavi\core\metadata.py", line 11, in <module>
    from mayavi.core.pipeline_info import PipelineInfo
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\mayavi\core\pipeline_info.py", line 12, in <module>
    from .utils import get_tvtk_dataset_name
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\mayavi\core\utils.py", line 2, in <module>
    import vtk
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\vtk.py", line 32, in <module>
    all_spec.loader.exec_module(all_m)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\vtkmodules\all.py", line 7, in <module>
    from .vtkCommonCore import *
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\vtkmodules\vtkCommonCore.py", line 9, in <module>
    from vtkCommonCorePython import *
ImportError: DLL load failed: The specified module could not be found.
```

I tried what @daltondm suggested there https://github.com/lambdaloop/anipose/issues/69 but with no luck. After this passage:
1. pip install numpy==1.19
2. conda uninstall mayavi
3. pip install vtk==8.1.2
4. pip install mayavi

The error now is this:

```
Traceback (most recent call last):
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\nini\Anaconda3\envs\dlc\Scripts\anipose.exe\__main__.py", line 7, in <module>
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\anipose\anipose.py", line 257, in label_3d
    from .label_videos_3d import label_videos_3d_all
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\anipose\label_videos_3d.py", line 16, in <module>
    from matplotlib.pyplot import get_cmap
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\matplotlib\pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\matplotlib\__init__.py", line 621, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\matplotlib\pyplot.py", line 236, in switch_backend
    current_framework = cbook._get_running_interactive_framework()
  File "C:\Users\nini\Anaconda3\envs\dlc\lib\site-packages\matplotlib\cbook\__init__.py", line 69, in _get_running_interactive_framework
    if wx and wx.GetApp():
AttributeError: module 'wx' has no attribute 'GetApp'
```

My environment has this modules:
```
# Name                    Version                   Build  Channel
_tflow_select             2.2.0                     eigen
absl-py                   0.13.0           py37haa95532_0
anipose                   1.0.1                    pypi_0    pypi
aniposelib                0.4.3                    pypi_0    pypi
apptools                  5.1.0                    pypi_0    pypi
astor                     0.8.1            py37haa95532_0
astunparse                1.6.3                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
blas                      1.0                         mkl
brotli                    1.0.9                    pypi_0    pypi
ca-certificates           2021.9.30            haa95532_1
cached-property           1.5.2                      py_0
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.10.8        py37haa95532_0
charset-normalizer        2.0.7                    pypi_0    pypi
clang                     5.0                      pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
configobj                 5.0.6                    pypi_0    pypi
coverage                  5.5              py37h2bbff1b_2
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.24          py37hd77b12b_0
dataclasses               0.8                pyh6d0b6a4_7
decorator                 4.4.2                    pypi_0    pypi
deeplabcut                2.2.0.2                  pypi_0    pypi
envisage                  6.0.1                    pypi_0    pypi
ffmpeg                    4.2.2                he774522_0
filterpy                  1.4.5                    pypi_0    pypi
flask                     2.0.2                    pypi_0    pypi
flask-compress            1.10.1                   pypi_0    pypi
flask-ipban               1.1.5                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.41.0                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
hdf5                      1.10.6               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
idna                      3.3                      pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imageio-ffmpeg            0.4.5                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        4.8.1            py37haa95532_0
importlib-resources       5.2.2                    pypi_0    pypi
intel-openmp              2021.3.0          haa95532_3372
ipython                   7.28.0                   pypi_0    pypi
itsdangerous              2.0.1                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    3.0.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
keras                     2.6.0                    pypi_0    pypi
keras-applications        1.0.8                      py_1
keras-preprocessing       1.1.2              pyhd3eb1b0_0
kiwisolver                1.3.2                    pypi_0    pypi
libprotobuf               3.17.2               h23ce68f_1
llvmlite                  0.37.0                   pypi_0    pypi
markdown                  3.3.4            py37haa95532_0
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.4.3                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mayavi                    4.7.3                    pypi_0    pypi
mkl                       2021.3.0           haa95532_524
mkl-service               2.4.0            py37h2bbff1b_0
mkl_fft                   1.3.0            py37h277e83a_2
mkl_random                1.2.2            py37hf11a4ad_0
mock                      4.0.3              pyhd3eb1b0_0
moviepy                   1.0.3                    pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
msgpack-numpy             0.4.7.1                  pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
numba                     0.54.1                   pypi_0    pypi
numexpr                   2.7.3                    pypi_0    pypi
numpy                     1.19.0                   pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
opencv-contrib-python     4.5.3.56                 pypi_0    pypi
opencv-python             4.5.3.56                 pypi_0    pypi
opencv-python-headless    4.5.3.56                 pypi_0    pypi
openssl                   1.1.1l               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
pandas                    1.3.3                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
patsy                     0.5.2                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.3.2                    pypi_0    pypi
pip                       21.2.4           py37haa95532_0
proglog                   0.1.9                    pypi_0    pypi
prompt-toolkit            3.0.20                   pypi_0    pypi
protobuf                  3.17.2           py37hd77b12b_0
psutil                    5.8.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyface                    7.3.0                    pypi_0    pypi
pygments                  2.10.0                   pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyreadline                2.1                      py37_1
python                    3.7.11               h6244533_0
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2021.3                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
ruamel-yaml               0.17.16                  pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
scikit-image              0.18.3                   pypi_0    pypi
scikit-learn              1.0                      pypi_0    pypi
scikit-video              1.1.11                   pypi_0    pypi
scipy                     1.7.1            py37hbe87c03_2
setuptools                58.0.4           py37haa95532_0
shapely                   1.7.1                    pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
sqlite                    3.36.0               h2bbff1b_0
statsmodels               0.13.0                   pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.6.0                    pypi_0    pypi
tensorflow-estimator      2.6.0                    pypi_0    pypi
tensorpack                0.11                     pypi_0    pypi
termcolor                 1.1.0            py37haa95532_1
tf-slim                   1.1.0                    pypi_0    pypi
threadpoolctl             3.0.0                    pypi_0    pypi
tifffile                  2021.10.12               pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.1.0                    pypi_0    pypi
traits                    6.3.1                    pypi_0    pypi
traitsui                  7.2.1                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.7                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
vtk                       8.1.2                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  2.0.1              pyhd3eb1b0_0
wheel                     0.37.0             pyhd3eb1b0_1
wincertstore              0.2              py37haa95532_2
wrapt                     1.12.1                   pypi_0    pypi
wxpython                  4.1.1                    pypi_0    pypi
zipp                      3.6.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
```

Can anyone help? Thank you very much!

**Comment by LWitter** [comment]
I'm having this issue as well. I can't seem to solve it any way I try. So, in effect the tutorial can not even be completed now, let alone analyzing my data.
I now tried to install with via this comment: https://github.com/lambdaloop/anipose/issues/40
But still doesn't work...

Working on windows 7
Anipose 1.0.1
deeplabcut 2.2.0.3
ipython 7.29.0
tensorflow 2.7.0
tensorflow-gpu 1.13.1
wxpython 4.0.4

Really hope someone can share an install file or list with combinations of versions of packages that works under windows. (I guess that's the issue here right, version conflicts between packages?)

**Comment by LWitter** [comment]
Small update: I have tried all kinds of combinations and iterations of path variables in windows. Nothing seems to resolve the issue.

Also, opening ipython and using import vtk results in an DLL error for vtk, which makes me guess it is just not properly installed?
